version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/patientenverwaltungdb
      - SPRING_DATASOURCE_USERNAME=patientenverwaltungowner
      - SPRING_DATASOURCE_PASSWORD=patientenverwaltungowner
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_DB=patientenverwaltungdb
      - POSTGRES_USER=patientenverwaltungowner
      - POSTGRES_PASSWORD=patientenverwaltungowner
    ports:
      - "35432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: