-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "SA" SALT '69d7b38ffbac2a05' HASH '97660023b90d196fbe729bde93daf58abe3c278a80b5c8145738f2a23dc7945b' ADMIN;         
CREATE SEQUENCE "PUBLIC"."ARZTPRAXEN_SEQ" START WITH 1 INCREMENT BY 50;       
CREATE SEQUENCE "PUBLIC"."ARZT_SEQ" START WITH 1 INCREMENT BY 50;             
CREATE SEQUENCE "PUBLIC"."BEHANDLUNGEN_SEQ" START WITH 1 INCREMENT BY 50;     
CREATE SEQUENCE "PUBLIC"."BEHANDLUNGSRAUM_SEQ" START WITH 1 INCREMENT BY 50;  
CREATE SEQUENCE "PUBLIC"."MITARBEITER_SEQ" START WITH 1 INCREMENT BY 50;      
CREATE SEQUENCE "PUBLIC"."PATIENT_SEQ" START WITH 1 INCREMENT BY 50;          
CREATE SEQUENCE "PUBLIC"."RECHNUNG_SEQ" START WITH 1 INCREMENT BY 50;         
CREATE SEQUENCE "PUBLIC"."WARTERAUM_SEQ" START WITH 1 INCREMENT BY 50;        
CREATE MEMORY TABLE "PUBLIC"."ARZT"(
    "ID" BIGINT NOT NULL,
    "STRASSE" CHARACTER VARYING(128),
    "STADT" CHARACTER VARYING(64),
    "PLZ" CHARACTER VARYING(4),
    "HAUS_NR" CHARACTER VARYING(6),
    "GEB_DATUM" DATE,
    "NAME" CHARACTER VARYING(255),
    "SVNR" BIGINT,
    "LKENNZAHL" CHARACTER VARYING(3),
    "OKENNZAHL" CHARACTER VARYING(4),
    "RUFNUMMER" CHARACTER VARYING(13),
    "ART" CHARACTER(1),
    "EMAIL" CHARACTER VARYING(255),
    "FACHGEBIET" ENUM('O', 'H', 'C', 'G', 'A'),
    "ARZTPRAXIS_ID" BIGINT,
    "AERZTE_ID" BIGINT
); 
ALTER TABLE "PUBLIC"."ARZT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ARZT;    
CREATE MEMORY TABLE "PUBLIC"."ARZTPRAXEN"(
    "ID" BIGINT NOT NULL,
    "STRASSE" CHARACTER VARYING(128),
    "STADT" CHARACTER VARYING(64),
    "PLZ" CHARACTER VARYING(4),
    "HAUS_NR" CHARACTER VARYING(6),
    "IST_KASSENARZT" BOOLEAN,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "LKENNZAHL" CHARACTER VARYING(3),
    "OKENNZAHL" CHARACTER VARYING(4),
    "RUFNUMMER" CHARACTER VARYING(13),
    "ART" CHARACTER(1)
);          
ALTER TABLE "PUBLIC"."ARZTPRAXEN" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ARZTPRAXEN;              
CREATE MEMORY TABLE "PUBLIC"."BEHANDLUNGEN"(
    "ID" BIGINT NOT NULL,
    "BEGINN" TIMESTAMP(6),
    "DIAGNOSE" CHARACTER VARYING(255),
    "ENDE" TIMESTAMP(6),
    "ARZT_ID" BIGINT NOT NULL,
    "BEHANDLUNGSRAUM_ID" BIGINT,
    "PATIENT_ID" BIGINT NOT NULL
); 
ALTER TABLE "PUBLIC"."BEHANDLUNGEN" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BEHANDLUNGEN;            
CREATE MEMORY TABLE "PUBLIC"."BEHANDLUNGSRAUM"(
    "ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "AUSSTATTUNG" CHARACTER VARYING(255),
    "IS_FREI" BOOLEAN,
    "BEHANDLUNGSRAUM_ID" BIGINT
);               
ALTER TABLE "PUBLIC"."BEHANDLUNGSRAUM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BEHANDLUNGSRAUM;         
CREATE MEMORY TABLE "PUBLIC"."BEHANDLUNGSRAUM_BEHANDLUNGEN"(
    "BEHANDLUNGSRAUM_ID" BIGINT NOT NULL,
    "BEHANDLUNGEN_ID" BIGINT NOT NULL
);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BEHANDLUNGSRAUM_BEHANDLUNGEN;            
CREATE MEMORY TABLE "PUBLIC"."MEDIKAMENTE"(
    "BEHANDLUNG_ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255),
    "WIRKSTOFF" CHARACTER VARYING(255)
);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MEDIKAMENTE;             
CREATE MEMORY TABLE "PUBLIC"."MITARBEITER"(
    "ID" BIGINT NOT NULL,
    "STRASSE" CHARACTER VARYING(128),
    "STADT" CHARACTER VARYING(64),
    "PLZ" CHARACTER VARYING(4),
    "HAUS_NR" CHARACTER VARYING(6),
    "GEB_DATUM" DATE,
    "NAME" CHARACTER VARYING(255),
    "SVNR" BIGINT,
    "LKENNZAHL" CHARACTER VARYING(3),
    "OKENNZAHL" CHARACTER VARYING(4),
    "RUFNUMMER" CHARACTER VARYING(13),
    "ART" CHARACTER(1),
    "EMAIL" CHARACTER VARYING(255) NOT NULL,
    "GEHALT" BIGINT,
    "ARZTPRAXIS_ID" BIGINT,
    "MITARBEITER_ID" BIGINT
);       
ALTER TABLE "PUBLIC"."MITARBEITER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_DE" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MITARBEITER;             
CREATE MEMORY TABLE "PUBLIC"."PATIENT"(
    "ID" BIGINT NOT NULL,
    "STRASSE" CHARACTER VARYING(128),
    "STADT" CHARACTER VARYING(64),
    "PLZ" CHARACTER VARYING(4),
    "HAUS_NR" CHARACTER VARYING(6),
    "GEB_DATUM" DATE,
    "NAME" CHARACTER VARYING(255),
    "SVNR" BIGINT,
    "LKENNZAHL" CHARACTER VARYING(3),
    "OKENNZAHL" CHARACTER VARYING(4),
    "RUFNUMMER" CHARACTER VARYING(13),
    "ART" CHARACTER(1),
    "VERSICHERUNGSART" ENUM('K', 'P')
);  
ALTER TABLE "PUBLIC"."PATIENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_FB" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PATIENT; 
CREATE MEMORY TABLE "PUBLIC"."RECHNUNG"(
    "ID" BIGINT NOT NULL,
    "BETRAG" FLOAT(53) NOT NULL,
    "BEZAHLT" BOOLEAN NOT NULL,
    "DATUM" TIMESTAMP(6),
    "ZAHLUNGSART" CHARACTER(1),
    "ARZT_ID" BIGINT NOT NULL,
    "PATIENT_ID" BIGINT NOT NULL
);      
ALTER TABLE "PUBLIC"."RECHNUNG" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_FE" PRIMARY KEY("ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RECHNUNG;
CREATE MEMORY TABLE "PUBLIC"."WARTERAUM"(
    "ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "ANZAHL_SITZPLAETZE" INTEGER NOT NULL,
    "WARTERAUM_ID" BIGINT
);  
ALTER TABLE "PUBLIC"."WARTERAUM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_48" PRIMARY KEY("ID");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.WARTERAUM;               
ALTER TABLE "PUBLIC"."WARTERAUM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" CHECK("ANZAHL_SITZPLAETZE" >= 0) NOCHECK;             
ALTER TABLE "PUBLIC"."MITARBEITER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" CHECK(("GEHALT" >= CAST(0 AS BIGINT))
    AND ("GEHALT" <= CAST(100000 AS BIGINT))) NOCHECK;       
ALTER TABLE "PUBLIC"."BEHANDLUNGSRAUM_BEHANDLUNGEN" ADD CONSTRAINT "PUBLIC"."UKCBEGEIE7L7RITPH5H3CCEM0LU" UNIQUE NULLS DISTINCT ("BEHANDLUNGEN_ID");          
ALTER TABLE "PUBLIC"."ARZT" ADD CONSTRAINT "PUBLIC"."UKI7CUYXTXAE2B3YMQ4I1Q32STS" UNIQUE NULLS DISTINCT ("ARZTPRAXIS_ID");    
ALTER TABLE "PUBLIC"."ARZT" ADD CONSTRAINT "PUBLIC"."FK65CIXDG1KOAG8T7VD3DX4MSTY" FOREIGN KEY("ARZTPRAXIS_ID") REFERENCES "PUBLIC"."ARZTPRAXEN"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BEHANDLUNGEN" ADD CONSTRAINT "PUBLIC"."FK_BEHANDLUNGSRAUM_2_BEHANDLUNG" FOREIGN KEY("BEHANDLUNGSRAUM_ID") REFERENCES "PUBLIC"."BEHANDLUNGSRAUM"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."MITARBEITER" ADD CONSTRAINT "PUBLIC"."FK_ARZTPRAXIS_2_MITARBEITER" FOREIGN KEY("MITARBEITER_ID") REFERENCES "PUBLIC"."ARZTPRAXEN"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."BEHANDLUNGEN" ADD CONSTRAINT "PUBLIC"."FK_PATIENT_2_BEHANDLUNG" FOREIGN KEY("PATIENT_ID") REFERENCES "PUBLIC"."PATIENT"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."BEHANDLUNGEN" ADD CONSTRAINT "PUBLIC"."FKGUGTELSGAFEMS7QB4SEDU7B5D" FOREIGN KEY("ARZT_ID") REFERENCES "PUBLIC"."ARZT"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."BEHANDLUNGSRAUM" ADD CONSTRAINT "PUBLIC"."FK_ARZTPRAXIS_2_BEHANDLUNGSRAUM" FOREIGN KEY("BEHANDLUNGSRAUM_ID") REFERENCES "PUBLIC"."ARZTPRAXEN"("ID") NOCHECK;            
ALTER TABLE "PUBLIC"."RECHNUNG" ADD CONSTRAINT "PUBLIC"."FK_RECHNUNG_2_PATIENT" FOREIGN KEY("PATIENT_ID") REFERENCES "PUBLIC"."PATIENT"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."BEHANDLUNGSRAUM_BEHANDLUNGEN" ADD CONSTRAINT "PUBLIC"."FKBUSSJW7TPBKCLSKWL5NU06IIV" FOREIGN KEY("BEHANDLUNGEN_ID") REFERENCES "PUBLIC"."BEHANDLUNGEN"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."WARTERAUM" ADD CONSTRAINT "PUBLIC"."FK_ARZTPRAXIS_2_WARTERAUM" FOREIGN KEY("WARTERAUM_ID") REFERENCES "PUBLIC"."ARZTPRAXEN"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."MEDIKAMENTE" ADD CONSTRAINT "PUBLIC"."FK_MEDIKAMENT_2_BEHANDLUNG" FOREIGN KEY("BEHANDLUNG_ID") REFERENCES "PUBLIC"."BEHANDLUNGEN"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."ARZT" ADD CONSTRAINT "PUBLIC"."FK_ARZTPRAXIS_2_ARZT" FOREIGN KEY("AERZTE_ID") REFERENCES "PUBLIC"."ARZTPRAXEN"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."RECHNUNG" ADD CONSTRAINT "PUBLIC"."FK_RECHNUNG_2_ARZT" FOREIGN KEY("ARZT_ID") REFERENCES "PUBLIC"."ARZT"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."MITARBEITER" ADD CONSTRAINT "PUBLIC"."FKDK8FQH3EAYPSG6G6UH4BNL6T3" FOREIGN KEY("ARZTPRAXIS_ID") REFERENCES "PUBLIC"."ARZTPRAXEN"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."BEHANDLUNGSRAUM_BEHANDLUNGEN" ADD CONSTRAINT "PUBLIC"."FKP2YMXGV76KB8TWH8PD7SB5D5P" FOREIGN KEY("BEHANDLUNGSRAUM_ID") REFERENCES "PUBLIC"."BEHANDLUNGSRAUM"("ID") NOCHECK;              
